Completed prep-css-flexbox. Vickram Kahlon
vkahlon/prep-1121-code-solutions pull request #8
Opened 2021-11-12 05:14 UTC by vkahlon

![flexbox 1](https://user-images.githubusercontent.com/47346471/141413403-92c0fe93-0f0f-41c7-a86e-510fcfd584f1.jpg)
![flexbox 2](https://user-images.githubusercontent.com/47346471/141413404-2914816d-560f-4338-a9a3-c9858a0d1f7d.jpg)
![flexbox 3](https://user-images.githubusercontent.com/47346471/141413405-1a45a0ea-b8ca-4479-8494-713508a7224a.png)
![flexbox 4](https://user-images.githubusercontent.com/47346471/141413406-db342dda-d5f9-493e-a99e-80140f98c828.png)

Note: I use a 1440p 21:9 ultrawide monitor which is why the search engine, tabs, and the overall bar are long.

2021-11-12 23:18 UTC, thebearingedge requested changes

2021-11-12 23:18 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +        flex-basis: calc(100% / 3);
Careful, `flex-basis` is meant to be used on items within a "flex container" (in this case the `div#card-deck`). Try creating a separate rule for `.card-container` and apply the `flex-basis` there.

2021-11-12 23:18 UTC, thebearingedge commented on prep-css-flexbox/display-flex.html
> +        flex-direction;
You can remove this `flex-direction` as the default for `display: flex;` is `row` without having to include the property.

2021-11-12 23:18 UTC, thebearingedge commented on prep-css-flexbox/flex-wrap.html
> +        flex-basis: calc(100% / 6);
Same here regarding the `flex-basis`

2021-11-12 23:18 UTC, thebearingedge commented on prep-css-flexbox/justify-content.html
> +        flex-basis: 25%;
Here as well for the `flex-basis`

2021-11-12 23:39 UTC, vkahlon commented on prep-css-flexbox/justify-content.html
> +        flex-basis: 25%;
reuploaded and made the necessary changes. thanks for the input!

2021-11-13 00:06 UTC, thebearingedge approved these changes

2021-11-13 00:09 UTC, merged